### ISSUE TITLE
Watcher-Listener delivery

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/runtime-watcher#2]
**Description**

The Change Detection mechanism is is an essential component in the[ new reconciler architecture](https://github.com/kyma-project/kyma/issues/13759). It is responsible to detect configurations provided by the customer and make them available on the management plane.

This mechanism consists of a two elements:

* a watcher component running inside of a customer cluster and detecting changees
* listener component running on the management plane side.

The watcher component It is following the [K8s operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) identifying configuration changes applied by the customer (via ConfigMaps). It propagates such changes to the listener component. The listener persists the change in the management plane. It will be picked up by the Kyma Operator who injects the customer configuration values into the related component CRs.

**Acceptance criteria**
- [x] #3
- [x] #5
- [x] #6
- [x] #62 
- [x] #67
- [ ] CI/CD pipelines are created and executed for code changes
- [ ] Threat modelling findings implemented (see https://github.com/kyma-project/lifecycle-manager/issues/144)
    - [x] https://github.com/kyma-project/lifecycle-manager/issues/147
    - [x] https://github.com/kyma-project/lifecycle-manager/issues/148
    - [x] https://github.com/kyma-project/lifecycle-manager/issues/149
- [ ] Operational requirements are covered
     - [ ] Exposing analysis and statistic relevant data via Prometheus endpoint
     - [ ] Logging of critical events
     - [x] Auditlog is integrated (only required for sensitive actions or data changes)
     - [ ] Operational test was executed and trouble-shooting guides were created
          - [ ]  What would happen if the watchable resources increase with time. Rate limiting or comparison based on filtered set timestamps?
- [ ] Documentation of the architectural design
- [ ] Microdelivery process established

**Issues**
https://github.com/kyma-project/kyma/issues/13759

**Appendix**
* CRD = Customt Resource Definition
* CR = Custom Resource
* BYOC = Bring your own cluster
* SKR = SAP Kyma Runtime
